import 'package:flutter/material.dart';
import 'package:fa_ai_agent/models/section.dart';
import 'package:fa_ai_agent/models/subscription_type.dart';
import 'package:fa_ai_agent/services/section_visibility_manager.dart';
import 'package:fa_ai_agent/widgets/animations/thinking_animation.dart';

class ReportContentLayout extends StatelessWidget {
  final List<Section> sections;
  final bool isAuthenticated;
  final bool isMag7Company;
  final SubscriptionType? userSubscriptionType;
  final bool isNarrow;
  final Widget Function(Section) buildSection;
  final Widget Function(String) headerView;
  final Map<String, Widget> sectionCache;
  final String tickerCode;
  final String language;

  const ReportContentLayout({
    Key? key,
    required this.sections,
    required this.isAuthenticated,
    required this.isMag7Company,
    required this.userSubscriptionType,
    required this.isNarrow,
    required this.buildSection,
    required this.headerView,
    required this.sectionCache,
    required this.tickerCode,
    required this.language,
  }) : super(key: key);

  String get _disclaimer =>
      'All information and analyses on this website are generated by various Artificial Intelligence/Machine Learning models and are intended solely as a general "research copilot"—not definitive financial advice. While the site strives to offer helpful insights, investors/traders/analysts/researchers are encouraged to conduct their own research or consult a qualified professional before making any financial decisions, as all investments involve market risk. By using this website, investors/traders/analysts/researchers acknowledge that neither the site nor its contributors shall be held responsible for any losses or damages resulting from the use of—or reliance upon—the AI-generated information provided. We appreciate everyone\'s understanding and encourage all to make informed, responsible, and profitable decisions.';

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: EdgeInsets.only(
        left: isNarrow ? 12.0 : 264.0,
        right: 12.0,
      ),
      child: LayoutBuilder(
        builder: (BuildContext context, BoxConstraints constraints) {
          final subscriptionType =
              userSubscriptionType ?? SubscriptionType.free;
          final shouldShowMetrics = isMag7Company ||
              (isAuthenticated && subscriptionType != SubscriptionType.free);

          return FutureBuilder<List<Section>>(
            future: SectionVisibilityManager.filterSections(
              sections,
              isAuthenticated,
              isMag7Company,
            ),
            builder: (context, sectionsSnapshot) {
              if (sectionsSnapshot.connectionState == ConnectionState.waiting) {
                return const Center(child: ThinkingAnimation());
              }

              final filteredSections = sectionsSnapshot.data ?? [];
              final contentSections = _buildContentSections(filteredSections);
              final accountingRedFlagsIndex = filteredSections
                  .indexWhere((s) => s.title == 'Accounting Red Flags');

              return Column(
                children: [
                  headerView(sections.first.title),
                  const SizedBox(height: 24),
                  _buildSectionsContainer(
                    contentSections,
                    accountingRedFlagsIndex,
                    shouldShowMetrics,
                    isNarrow,
                  ),
                ],
              );
            },
          );
        },
      ),
    );
  }

  List<Widget> _buildContentSections(List<Section> filteredSections) {
    return filteredSections
        .map((section) => buildSection(section))
        .where((widget) => widget is! SizedBox || (widget).width != 0)
        .toList();
  }

  Widget _buildSectionsContainer(
    List<Widget> contentSections,
    int accountingRedFlagsIndex,
    bool shouldShowMetrics,
    bool isNarrow,
  ) {
    return Container(
      color: Colors.white,
      child: isNarrow
          ? _buildNarrowLayout(contentSections, shouldShowMetrics)
          : _buildWideLayout(
              contentSections,
              accountingRedFlagsIndex,
              shouldShowMetrics,
            ),
    );
  }

  Widget _buildNarrowLayout(
      List<Widget> contentSections, bool shouldShowMetrics) {
    return Padding(
      padding: const EdgeInsets.all(0),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          ...contentSections,
          const SizedBox(height: 48),
          Container(
            width: double.infinity,
            height: 1,
            color: Colors.grey[300],
          ),
          const SizedBox(height: 16),
          Text(
            _disclaimer,
            style: TextStyle(
              color: Colors.grey[600],
              fontSize: 12,
              height: 1.5,
            ),
          ),
          const SizedBox(height: 32),
        ],
      ),
    );
  }

  Widget _buildWideLayout(
    List<Widget> contentSections,
    int accountingRedFlagsIndex,
    bool shouldShowMetrics,
  ) {
    // Find the Financial Metrics section
    final financialMetricsIndex =
        sections.indexWhere((s) => s.title == 'Financial Metrics');
    final financialMetrics = financialMetricsIndex >= 0 &&
            financialMetricsIndex < contentSections.length
        ? contentSections[financialMetricsIndex]
        : null;

    // Split sections into two groups:
    // 1. Sections before Accounting Red Flags (left side with metrics)
    // 2. Sections from Accounting Red Flags onwards (full width)
    final sectionsBeforeRedFlags = accountingRedFlagsIndex >= 0
        ? contentSections.take(accountingRedFlagsIndex).toList()
        : contentSections;
    final sectionsAfterRedFlags = accountingRedFlagsIndex >= 0
        ? contentSections.skip(accountingRedFlagsIndex).toList()
        : [];

    // Remove Financial Metrics from left side sections
    final leftSections = sectionsBeforeRedFlags
        .where((section) => section != financialMetrics)
        .toList();

    return Padding(
      padding: const EdgeInsets.symmetric(horizontal: 0),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          // Top row with left content and metrics
          Row(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              // Left side - sections before Accounting Red Flags
              Expanded(
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    ...leftSections.map((section) => Column(
                          children: [
                            section,
                            const SizedBox(height: 48),
                          ],
                        )),
                  ],
                ),
              ),
              // Right side - Financial Metrics
              if (financialMetrics != null) ...[
                const SizedBox(width: 24),
                SizedBox(
                  width: 280,
                  child: Column(
                    children: [
                      financialMetrics,
                      const SizedBox(height: 48),
                    ],
                  ),
                ),
              ],
            ],
          ),
          // Full width sections (Accounting Red Flags onwards)
          ...sectionsAfterRedFlags.map((section) => Column(
                children: [
                  section,
                  const SizedBox(height: 48),
                ],
              )),
          // Footer
          Container(
            width: double.infinity,
            height: 1,
            color: Colors.grey[300],
          ),
          const SizedBox(height: 16),
          Padding(
            padding: const EdgeInsets.symmetric(horizontal: 12),
            child: Text(
              _disclaimer,
              style: TextStyle(
                color: Colors.grey[600],
                fontSize: 12,
                height: 1.5,
              ),
            ),
          ),
          const SizedBox(height: 32),
        ],
      ),
    );
  }

  Widget getMetricsTable(bool isNarrow) {
    return const SizedBox.shrink();
  }
}
