// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB36U-Oo5X8X2otxd9d3v0rZxmxr37hgtU',
    appId: '1:754540534666:web:b64ab809db245190b38673',
    messagingSenderId: '754540534666',
    projectId: 'fa-ai-agent-app',
    authDomain: 'fa-ai-agent-app.firebaseapp.com',
    storageBucket: 'fa-ai-agent-app.firebasestorage.app',
    measurementId: 'G-WEXEKDRYHW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCbIB9yPtWBTGas7klNpluTm6P8ODHRTM',
    appId: '1:754540534666:android:60c07fb04046acb8b38673',
    messagingSenderId: '754540534666',
    projectId: 'fa-ai-agent-app',
    storageBucket: 'fa-ai-agent-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYVfsdFnFE158pNp0CKtX9zvORpquKvNI',
    appId: '1:754540534666:ios:eb57c6187429520db38673',
    messagingSenderId: '754540534666',
    projectId: 'fa-ai-agent-app',
    storageBucket: 'fa-ai-agent-app.firebasestorage.app',
    iosBundleId: 'com.example.faAiAgent',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYVfsdFnFE158pNp0CKtX9zvORpquKvNI',
    appId: '1:754540534666:ios:eb57c6187429520db38673',
    messagingSenderId: '754540534666',
    projectId: 'fa-ai-agent-app',
    storageBucket: 'fa-ai-agent-app.firebasestorage.app',
    iosBundleId: 'com.example.faAiAgent',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB36U-Oo5X8X2otxd9d3v0rZxmxr37hgtU',
    appId: '1:754540534666:web:8b3a9081389f7160b38673',
    messagingSenderId: '754540534666',
    projectId: 'fa-ai-agent-app',
    authDomain: 'fa-ai-agent-app.firebaseapp.com',
    storageBucket: 'fa-ai-agent-app.firebasestorage.app',
    measurementId: 'G-CHYLNWXC2N',
  );
}
